name: Build
on: 
    workflow_run: 
        workflows: ["CI"]
        types: 
            - completed
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: npm ci
            - run: npm build